issue-639: Current day warnings widget
fmidev/weather-app pull request #737
Opened 2024-12-18 14:22 UTC by stembitf

2024-12-19 07:37 UTC, geosaaga requested changes
These issues could be fixed if you have time. The same warning is repeated multiple times (should show wind warning or traffic warning only once).

And when only one warning then it should show time period when warning is valid.

Wind warning for sea areas (Utö) is missing wind direction and wind speed also. Should be displayed same way like here

https://www.ilmatieteenlaitos.fi/varoitukset

<img width="344" alt="Näyttökuva 2024-12-19 kello 9 29 42" src="https://github.com/user-attachments/assets/61a7abd1-76c4-420d-b3e3-8747c7e51810" />

2024-12-19 09:25 UTC, stembitf commented
The widget displays all warnings it receives from https://weather-app-warnings-backend-prod.out.ocp.fmi.fi/v1/warnings?...

These are warnings of current day and of next few days.

Should the wind direction and speed be displayed like this in the widget?:
<img width="34" alt="Screenshot 2024-12-19 at 11 22 48" src="https://github.com/user-attachments/assets/959c65bd-0da7-4913-8252-be04df064963" />

No extra text needed?


> These issues could be fixed if you have time. The same warning is repeated multiple times (should show wind warning or traffic warning only once).
> 
> And when only one warning then it should show time period when warning is valid.
> 
> Wind warning for sea areas (Utö) is missing wind direction and wind speed also. Should be displayed same way like here
> 
> https://www.ilmatieteenlaitos.fi/varoitukset
> 
> <img alt="Näyttökuva 2024-12-19 kello 9 29 42" width="344" src="https://private-user-images.githubusercontent.com/8179955/397266348-61a7abd1-76c4-420d-b3e3-8747c7e51810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDAwNDQsIm5iZiI6MTczNDU5OTc0NCwicGF0aCI6Ii84MTc5OTU1LzM5NzI2NjM0OC02MWE3YWJkMS03NmM0LTQyMGQtYjNlMy04NzQ3YzdlNTE4MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMDkxNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjU5OTM2ZGU2NzNiODE2N2Q5M2ViMzIyOWEzN2RkZDIyM2VlNDc5ZmNlYzczNzk0YTIyMjI4NjM4NGFhNGMzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OFSyXbFCAJ8xTrcfuWOoRscMptYESwVb_Fie5jX8gIc">

2024-12-19 09:56 UTC, stembitf commented
OK

> You should show only current day warnings in this widget, not next few days. 5 day warnings will be implemented later.
> 
> Yes, replace standard wind warning icon with that icon (wind arrow and wind speed as number).

2024-12-19 13:31 UTC, stembitf commented
Requested changes done.
But @geosaaga could still test it before merge.

2024-12-19 13:32 UTC, geosaaga commented
Yes, I will continue from here. Thanks!

2024-12-19 13:49 UTC, stembitf commented
I just tried to merge android-main into this branch.
The merge conflicts do not look bad fortunately.

But I did not finish the merge - just in case.

2025-01-08 09:15 UTC, AnttiRumpunen approved these changes
ok

2025-01-23 11:09 UTC, geosaaga approved these changes

2025-01-27 07:37 UTC, merged